name: govulncheck.yml
on:
  schedule:
    - cron: '0 0 * * *'
  push:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: get TDengine
        run: |
          wget "${{ secrets.NIGHTLY_TDENGINE_ENTERPRISE_BASE_URL }}/tsdb-nightly-main.tar.gz?v=$(date +%s)" -O tsdb-nightly-main.tar.gz

      - name: install
        run: |
          tar -zxf tsdb-nightly-main.tar.gz
          cd tsdb-nightly-main
          ls -al
          sudo ./install.sh

      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version: 'stable'

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run vulnerability scan
        run: |
          govulncheck -show verbose -test ./...  | tee govulncheck.out
          if grep -q "Vulnerability #" govulncheck.out; then
            echo "❌ Vulnerabilities found"
            exit 1
          fi
          echo "✅ No vulnerabilities found"

      - name: feishu_report
        if: failure() && github.event_name == 'schedule'
        env:
          FEISHU_WEBHOOK_URL: ${{ secrets.FEISHU_WEBHOOK_URL }}
        run: |
          REPO_NAME=${GITHUB_REPOSITORY}
          WORKFLOW_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"

          curl -X POST $FEISHU_WEBHOOK_URL \
               -H 'Content-Type: application/json' \
               -d "{
                 \"msg_type\": \"interactive\",
                 \"card\": {
                   \"config\": {\"wide_screen_mode\": true},
                   \"header\": {\"title\": {\"tag\": \"plain_text\",\"content\": \"Dependency Scan Alert\"}},
                   \"elements\": [
                     {
                       \"tag\": \"div\",
                       \"text\": {
                         \"tag\": \"lark_md\",
                         \"content\": \"${REPO_NAME} Dependency check failed. [View Workflow](${WORKFLOW_URL})\"
                       }
                     }
                   ]
                 }
               }"
